### ISSUE TITLE
How to add functionality

### ISSUE THREAD

**Issue by larsontim12** [akarzazi/SSMSPlus#1]
Hi,

I like your project nice work! I would like to add some functionality that when I right click on a table in the object explorer  in will bring up a menu item in the context menu that I add.  I see in the code that in the QueryTracker there is code called tableMenuItem but I can't figure out how I can get that to work.

Any help would be appreciated.

Thanks -Tim

**Comment by akarzazi** [comment]
Hi Tim,
Thanks for your interest.

I intended to add context menu on the object explorer at some point.
I got it to work but for some forgotten reason I rolled-back the idea.
The `tableMenuItem` is dead code.

You can find here, a great sample on how to add context menus : 
https://github.com/ErikEJ/SqlCeToolbox/blob/master/src/API/Scripter/Connect.cs

What functionality would you like to add ?

Adel,

**Comment by akarzazi** [comment]
Hi Tim,
I've added now a "Contribute" section to the readme doc [https://github.com/akarzazi/SSMSPlus#contributing](https://github.com/akarzazi/SSMSPlus#contributing).

You'll find some tips and guidance for debugging.

Hope it will help you to get started.
