### ISSUE TITLE
Open Query Editor from a toolbar button

### ISSUE THREAD

**Issue by gaberad** [akarzazi/SSMSPlus#13]
Hi, I was wondering if the following was possible/if you could implemented it:

Essentially I'm looking for a way to open the Query Editor (?, not sure of the exact name) without having to drill down into the database tables.

It's the one where you right click on a table and go 'Edit Top 200 Rows...", and that opens the Query Editor in a new tab (as opposed to the Query Designer, which opens in a popup window).

Was wondering if a 'query-less' version of that be called from the toolbar menus/toolbar button? 'query-less' in this case meaning with an empty query pane, or if that's not possible then maybe a 'select top 200...' against a default table in master/msdb.

**Comment by akarzazi** [comment]
You can open the query editor from the server nodes and the database node.
Right click on the node -> then new query

**Comment by gaberad** [comment]
Oh, yeah, I know about that one, but it's not what I'm referring to.

It's the "edit top 200 rows" option, where you can edit data directly in the results grid.

It looks like it's also called the 'Query Designer', but it opens in a new tab, rather than an a pop up.

Does that make sense? I can post screenshots when I'm back home.

**Comment by gaberad** [comment]
This is what I mean:
![image](https://user-images.githubusercontent.com/1579155/100168417-199e4e80-2f26-11eb-956c-ca414a151219.png)

![image](https://user-images.githubusercontent.com/1579155/100168437-258a1080-2f26-11eb-8cba-a973c4c3961f.png)

**Comment by akarzazi** [comment]
Okay, I understand.
Why opening this view in a pop up is a big deal ?

**Comment by gaberad** [comment]
That's because the popup doesn't actually let you execute sql queries & view/edit the results, it only helps you construct the queries e.g. for views etc.

I find that in some cases it's easier to edit data directly in the results grid, so I was looking for a way to open the tabbed query designer, like from a toolbar button, without having to drill down all the way to the tables > edit top 200...

**Comment by akarzazi** [comment]
Sorry, not the kind of feature in the scope.
https://github.com/akarzazi/SSMSPlus#project-goals
