### ISSUE TITLE
Marking Successfully executed scripts - Enhancement

### ISSUE THREAD

**Issue by Kveto** [akarzazi/SSMSPlus#14]
Hi Adel.

I found SSMSPlus extension very usefull. 
You did great work!

I am wandering if we can check the status of the script execution (successfully executed or with errors), too.

After while the list of scripts in History may have a lot of items with no big use (for instance if we select incorrect part of the script and it fails to execute, etc), the really important ones are successfully executed scripts with no errors.

Is there a way how to find out (for instance in CommandEvents_AfterExecute event, or by running some query, or reading it from the Message text/the Status text) if script run successfully? Thee really important ones are successfully executed scripts, (even though the full history is very good, too :-)

Thank you in advance for your response.

Best Regards
Kveto Tulipan

**Comment by Kveto** [comment]
Hi Adel,

Thanks for your response, I understand you probably agree it would be an usefull feature to have a possibility 
to display all or just successfully executed scripts.

On that note - do you know how to access the information from Message window or the status bar information
after the query is executed? I cannot find anything related to this and I am very curious how to do it.
The only think I can access is the main Status bar text, which is not relevant to this.

Please let me know if you have a second.

Thank you in advance.

Kveto Tulipan

**Comment by akarzazi** [comment]
Hi Kveto,
Thank you for your involvement and I'm glad you find this extension useful.

Indeed, the query status is an important information.
But we cannot obtain it with the current interception point (CommandEvents_*).

I've looked around this in the past, but I didn't manage to find a clean way to do it.

**Comment by Kveto** [comment]
Hi Adel
Thank you for your response.
Best RegardsKveto
    On Monday, 11 October 2021, 08:10:53 BST, Adel KARZAZI ***@***.***> wrote:  
 
 


Hi Kveto,
Thank you for your involvement and I'm glad you find this extension useful.

Indeed, the query status is an important information.
But we cannot obtain it with the current interception point (CommandEvents_*).

I've looked around this in the past, but I didn't manage to find a clean way to do it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
