### ISSUE TITLE
Bug - Unsaved documents cannot be cut or copied to the clipboard from the Miscellaneous Files project.

### ISSUE THREAD

**Issue by pregress** [akarzazi/SSMSPlus#16]
In execution history, when selecting part of a query and pressing <kbd>ctrl</kbd>+<kbd>c</kbd>. I receive the following error:

![image](https://user-images.githubusercontent.com/1079843/155081166-287a2b47-26a2-485e-a524-f886f9039a02.png)

**SSMS version**: 

- SQL Server Management Studio 15.0.18390.0
- SQL Server Management Objects (SMO) 16.100.46521.71
- Microsoft Analysis Services Client Tools	15.0.19714.0
- Microsoft Data Access Components (MDAC)	10.0.19041.1
- Microsoft MSXML 3.0 6.0 
- Microsoft .NET Framework 4.0.30319.42000
- Operating System 10.0.19042

**SSMS Plus version**:  4.0

**Comment by rikin-patel435** [comment]
Can please try to untick the following option and restart SSMS.
Tools > Options
![image](https://user-images.githubusercontent.com/27278348/155086149-82a0db45-2d4a-44d9-89cf-a1e56d53f166.png)

**Comment by pregress** [comment]
That solves it, but should the extension take care of it? 
Since "Show Miscellaneous files in Solution Explorer" is default SSMS behaviour.

**Comment by rikin-patel435** [comment]
Thanks for the updates, but even regdate extension also has the same issue, and they are also not able to handle this kind of issue so in our case, currently, this is only a workaround.
