### ISSUE TITLE
Access to the Results pane?

### ISSUE THREAD

**Issue by DanielEms2** [akarzazi/SSMSPlus#17]
Hi @akarzazi, I love this extension!

Have you found a way to access the SSMS **Results pane**?  

I want to remove the NULL string from the Text Results.  I haven't seen any SSMS extensions that can do this, so it might not be possible...

Thanks!!!

**Comment by akarzazi** [comment]
From what I remember, I've tried with no success.

Also, this kind of feature in the scope.
https://github.com/akarzazi/SSMSPlus#project-goals
