### ISSUE TITLE
Context menu on Object Explorer to connect current document to a different database/server

### ISSUE THREAD

**Issue by AScriver** [akarzazi/SSMSPlus#23]
A feature from SSMSBoost that I think could fit nicely here. 

![SetAsActiveConnection](https://user-images.githubusercontent.com/34779562/217886722-6cb873c6-7be7-47a6-9b93-4b80a22d3a62.png)

**Comment by AScriver** [comment]
Trying to implement this on my own at the moment. However, I'm finding that this probably isn't the best place to start learning C#...

**Comment by akarzazi** [comment]
Sorry, not the kind of feature in the scope.
https://github.com/akarzazi/SSMSPlus#project-goals
