### ISSUE TITLE
No entries in history

### ISSUE THREAD

**Issue by h3xen** [akarzazi/SSMSPlus#24]
SQL : Microsoft SQL Server 2016 (SP3-OD) (KB5006943) - 13.0.6404.1 (X64)   Oct 18 2021 09:37:01   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor) 

SSMS : C:\Program Files (x86)\Microsoft SQL Server Management Studio 18\Common7\IDE

![image](https://github.com/akarzazi/SSMSPlus/assets/9263663/69a311f6-c94d-4ea3-96a9-c19652b957d1)

"LocalDate               ";"Level         ";"Category                                                    ";Text
"2024-02-05 08:56:25.48  ";"Information   ";"SSMSPlusDb.DbUpdate.DbUpdater                               ";Build version is up to date, current 5, target 5
"2024-02-05 08:57:00.62  ";"Error         ";"SSMSPlusHistory.Services.QueryTracker                       ";Error on BeforeExecute tracking
"2024-02-05 08:57:25.34  ";"Error         ";"SSMSPlusHistory.Services.QueryTracker                       ";Error on BeforeExecute tracking
"2024-02-05 08:57:30.94  ";"Error         ";"SSMSPlusHistory.Services.QueryTracker                       ";Error on BeforeExecute tracking
"2024-02-05 08:58:20.20  ";"Error         ";"SSMSPlusHistory.Services.QueryTracker                       ";Error on BeforeExecute tracking
"2024-02-05 08:59:23.78  ";"Error         ";"SSMSPlusHistory.Services.QueryTracker                       ";Error on BeforeExecute tracking
"2024-02-05 08:59:55.67  ";"Error         ";"SSMSPlusHistory.Services.QueryTracker                       ";Error on BeforeExecute tracking
"2024-02-05 09:00:12.74  ";"Error         ";"SSMSPlusHistory.Services.QueryTracker                       ";Error on BeforeExecute tracking
"2024-02-05 09:00:38.07  ";"Error         ";"SSMSPlusHistory.Services.QueryTracker                       ";Error on BeforeExecute tracking

**Comment by rikinpatel13** [comment]
Hi @h3xen 
Can you please provide more info like screenshot, which version of sql server, steps to produce etc.

**Comment by h3xen** [comment]
@patelriki13 i update first comment

**Comment by akarzazi** [comment]
Cannot reproduce.
Please try with SSMS 20
