### ISSUE TITLE
Support for SSMS 20 release

### ISSUE THREAD

**Issue by jhigh2000** [akarzazi/SSMSPlus#25]
Are there any plans for an SSMS 20 compatible release now that it's generally available? I tried to make this extension work with SSMS 20 (it did, partially), but I don't know enough about extension development to get it over the finish line.

**Comment by fredclown** [comment]
I would love to see this work with v20 as well. Such a handy extension.

**Comment by akarzazi** [comment]
Enjoy : )

https://github.com/akarzazi/SSMSPlus/releases/tag/6.0
