### ISSUE TITLE
Error When Copying

### ISSUE THREAD

**Issue by fredclown** [akarzazi/SSMSPlus#26]
I have only verified this in SSMS 19. If you have the Execution History tab open and you also create at least one new query tab but haven't saved that tab as a .sql file when you go to copy text from the Execution History tab using ctrl+c after highlighting a history row and selecting the SQL text you get an error. If you right click the selected SQL text and click copy you don't get the error. If you save the query tab to a file then the error does not present. The error is below.

Error Text:
Unsaved documents cannot be cut or copied to the clipboard from the Miscellaneous Files project. You must save the unsaved documents(s) before cutting or copying them.

![error](https://github.com/akarzazi/SSMSPlus/assets/549541/40f6aa34-6cdd-451b-88be-75c9b00df077)

**Comment by rikinpatel13** [comment]
Can you please try following solution.

![image](https://github.com/akarzazi/SSMSPlus/assets/3973924/6b13cc3a-7e6f-47c7-a922-11e15f393b63)

**Comment by fredclown** [comment]
Yep. That did it.
