### ISSUE TITLE
VS2022: Cannot build

### ISSUE THREAD

**Issue by ZedZipDev** [akarzazi/SSMSPlus#28]
I am trying to build the extension in VS2022 but received many errors. How to build?

**Comment by akarzazi** [comment]
Can you provide more details on the errors ?
see readme file for build instructions.

**Comment by adelsonrms** [comment]
I had same problem..

To me, I have follow error 

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The target "IncludeVSIXItems" does not exist in the project.	SSMSPlus
```

**Comment by akarzazi** [comment]
maybe you are missing visual studio components for extensions on you installation.
run visual studio installer and add this : 
![image](https://github.com/user-attachments/assets/1583019d-06f7-4e17-80af-b8d13740a0a5)

you should see these menus :
![image](https://github.com/user-attachments/assets/9d2a0a67-8d5f-4ded-be2c-c2a6db7bd2ae)

![image](https://github.com/user-attachments/assets/5f3ca437-6797-4c5b-a8cc-39d2d5c44758)
