### ISSUE TITLE
Debug in VS 2022 + SSMS 20.2 error

### ISSUE THREAD

**Issue by adelsonrms** [akarzazi/SSMSPlus#29]
When trying to debug the extension with SSMS 20.2 using VS 2022 17, the button is presented but the event is not invoked.

When examining the log in the VS log file at "`file:///C:/Users/{user}/AppData/Roaming/Microsoft/AppEnv/15.0/ActivityLog.xml`" I find the following indicative message.

`<description>CreateInstance failed for package [ArmsSSMSGitUtilPackage]Source: &apos;mscorlib&apos; Description: Could not load file or assembly &apos;Microsoft.VisualStudio.Shell.15.0, Version=17.0.0.0,`

**Comment by akarzazi** [comment]
maybe related to https://github.com/akarzazi/SSMSPlus/issues/28
