### ISSUE TITLE
it seems your installation guide is outdated

### ISSUE THREAD

**Issue by N0rimaki** [akarzazi/SSMSPlus#6]
When i download and extract this tag : https://github.com/akarzazi/SSMSPlus/releases/tag/2.3 there are a bunch of files when i create the Folder Extensions and place it into it i will have the SSMSPlus tab in the Studio 18.1.
Schema Search work
History does not work
it seems a bit odd, am i'm wrongdoing anything?

**Comment by akarzazi** [comment]
Hi,
Thankx for reporting the issue.
There was indeed a problem in the 2.3 package.

I just published a new version, https://github.com/akarzazi/SSMSPlus/releases/tag/2.4

I tested it on SSMS 18.5 and it works fine.

Please let me know if the issue is fixed.
